<!--About One Start-->
<section class="about-one py-5">
    <div class="about-one-bg wow slideInRight" data-wow-delay="100ms" data-wow-duration="2500ms"
         style="background-image: url(template/assets/images/about-one-bg.png);"></div>
         
         <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-6 mb-3">
                    <img class="img-fluid rounded" src="template/assets/images/about-img.jpg" alt="img">
                  </div>
              <div class="col-md-12 col-lg-6 align-self-center" style="color: black">
                <h3 class="section-title__title">About The Company</h3>
                <p class="about-one__text-2">Business, Technology and Process Inc. (BTP), a Canadian IT solution provider. btp has number of Qualified Accountants, IT Professionals and few Strategic partners.</p>
                <ul class="text-custom">
                    <li style="font-weight: 600">
                        Our Strategic Partners
                    </li>
                    <li>
                            In Canada: Accounting Harbor (Accounting Firm)
                    </li>
                    <li>
                            In USA: Synergy Technology Solutions LLC (IT firm and our global distributor)
                    </li>
                    <li>
                            In Bangladesh: Howladar Yunus and Co. (Audit Firm)
                    </li>
                    <li>
                            In Bangladesh: btp Bangladesh Ltd. (IT Firm)
                    </li>
                </ul>
              </div>
             
            </div>
          </div>
</section>
<!--About One End-->

 <!--Why choose Us Start-->
 <section id="Why-choose" class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-6 align-self-center mb-4">
            <h3 class="section-title__title mb-4">Why choose Us</h3>
            <ul class="text-custom" style="color: black">
                <li>
                    <i class="fas fa-angle-double-right"></i>	Our consultants have extensive knowledge in managing various operations and implementing ERP
                </li>
                <li>
                    <i class="fas fa-angle-double-right"></i>	We understand business process and the importance of data security
                </li>
                <li>
                    <i class="fas fa-angle-double-right"></i>	We can help you to reduce your cost at significant level
                </li>
                <li>
                    <i class="fas fa-angle-double-right"></i>	Our online features can save your time and investment on equipment
                </li>
                <li>
                    <i class="fas fa-angle-double-right"></i>	We help clients to improve efficiencies so that they can focus into their core business
                </li>
            </ul>
        </div>
        <div class="col-md-12 col-lg-6">
          <img class="img-fluid rounded" src="template/assets/images/image5.jpeg" alt="img">
        </div>
      </div>
    </div>
   </section>
<!--Why choose Us End-->