<!--Portfolio Start-->
<section id="portfolio" class="portfolio" style="padding: 36px 0 36px;">
    <div class="container">
        <div class="section-title text-center">
            <h2 class="section-title__title mb-4">Our Product</h2>
            <h2 class="text-[20px]">SBP(Standard Business Practice)</h2>

            <p style="font-size: 18px">
                The name of our ERP solution is SBP. It is a cloud based which defines the business process itself.
            </p>

        </div>
    
            
            
        <div class="">
          <div class="card-body">
            <div class="flex flex-column mb-5 faq-section">
              <div class="row">
                <div class="col-md-12">
                  <div>
                      <h5 style="font-weight: 900">The distinctive feature of SBP are</h5>
                      <ul class="text-custom">
                          <li>
                              <i class="fas fa-angle-double-right"></i>	SBP modules are integrated, complies with all accounting standard and norms.
                          </li>
                          <li>
                              <i class="fas fa-angle-double-right"></i>	User friendly and easy to train resources.
                          </li>
                          <li>
                              <i class="fas fa-angle-double-right"></i>	Ensure strong internal control, secure database and returns very low audit risk.
                          </li>
                          <li>
                              <i class="fas fa-angle-double-right"></i>	The rules and privileges are well defined and users are restricted by their assigned rules..
                          </li>
                          <li>
                              <i class="fas fa-angle-double-right"></i>	Build on restful API making the server communication very lightweight and faster.
                          </li>
                          <li>
                              <i class="fas fa-angle-double-right"></i>	Capable to run with any web browser.
                          </li>
                      </ul>
                  </div>

                  <div class="row mt-4">
                    <div class="col-lg-7 col-md-12 align-self-center">
                      <h2 class=" mb-3 text-center">SBP Modules</h2>
                      <div id="accordion">
                        <div class="card">
                          <div class="card-header" id="heading-1">
                            <h5 class="mb-0">
                              <a role="button" data-toggle="collapse" href="#collapse-1" aria-expanded="true" aria-controls="collapse-1">
                                  Financial Accounting
                                                </a>
                            </h5>
                          </div>
                          <div id="collapse-1" class="collapse show" data-parent="#accordion" aria-labelledby="heading-1">
                            <div class="card-body">
                              <ul class="text-custom">
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>  General Ledger (user can use SBP Global or may create own Chart of Accounts)
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Accounts Receivable 
                                  </li>
                                  <li>
                                       <i class="fas fa-angle-double-right"></i>	Accounts Payable 
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>  Fixed Assets Management (Maintains Asset Master and calculates both Accounting and tax depreciation)
                                  </li>
                                  <li>
                                    <i class="fas fa-angle-double-right"></i>	Standard Report 
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="heading-2">
                            <h5 class="mb-0">
                              <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-2" aria-expanded="false" aria-controls="collapse-2">
                                  Material Management
                                                </a>
                            </h5>
                          </div>
                          <div id="collapse-2" class="collapse" data-parent="#accordion" aria-labelledby="heading-2">
                            <div class="card-body">
                              <ul class="text-custom">
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Procurement (Maintains  AP Master)
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Inventory Management (Maintains Material Master)
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Production (Maintains Production Process)
                                  </li>
                                  <li>
                                    <i class="fas fa-angle-double-right"></i>	Standard Report 
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="heading-3">
                            <h5 class="mb-0">
                              <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-3" aria-expanded="false" aria-controls="collapse-3">
                                  Sales and Distribution (Maintains  AR Master)
                                                </a>
                            </h5>
                          </div>
                          <div id="collapse-3" class="collapse" data-parent="#accordion" aria-labelledby="heading-3">
                            <div class="card-body">
                              <ul class="text-custom">
                                  <li>
                                      <i class="fas fa-angle-double-right"></i> 	Customer master data
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Pricing condition
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Process sales order (starting from order receipt, materials delivered or services providing and invoices to customer)
                                  </li>
                                  <li>
                                    <i class="fas fa-angle-double-right"></i>	Standard Report 
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="heading-4">
                            <h5 class="mb-0">
                              <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-4" aria-expanded="false" aria-controls="collapse-4">
                                  Management Accounting (Profitability Analysis)
                                                </a>
                            </h5>
                          </div>
                          <div id="collapse-4" class="collapse" data-parent="#accordion" aria-labelledby="heading-4">
                            <div class="card-body">
                              <ul class="text-custom">
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Project Cost Tracking
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Cost Center Accounting
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Profit Center Accounting 
                                  </li>
                                  <li>
                                    <i class="fas fa-angle-double-right"></i>	Standard Report 
                                </li>
                                 
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="heading-5">
                            <h5 class="mb-0">
                              <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-5" aria-expanded="false" aria-controls="collapse-5">
                                  Production Planning
                                                </a>
                            </h5>
                          </div>
                          <div id="collapse-5" class="collapse" data-parent="#accordion" aria-labelledby="heading-5">
                            <div class="card-body">
                              <ul class="text-custom">
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Routing capacity planning
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i> 	Material requirement planning
                                  </li>
                                  <li>
                                    <i class="fas fa-angle-double-right"></i>	Standard Report 
                                </li>
                                 
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="heading-6">
                            <h5 class="mb-0">
                              <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-6" aria-expanded="false" aria-controls="collapse-6">
                                  Human Resource Planning
                                                </a>
                            </h5>
                          </div>
                          <div id="collapse-6" class="collapse" data-parent="#accordion" aria-labelledby="heading-6">
                            <div class="card-body">
                              <ul class="text-custom">
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Attendance
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Payroll
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Compliance and benefits
                                  </li>
                                  <li>
                                    <i class="fas fa-angle-double-right"></i>	Standard Report 
                                </li>
                                 
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="heading-7">
                            <h5 class="mb-0">
                              <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-7" aria-expanded="false" aria-controls="collapse-7">
                                  Rental Management System
                                                </a>
                            </h5>
                          </div>
                          <div id="collapse-7" class="collapse" data-parent="#accordion" aria-labelledby="heading-7">
                            <div class="card-body">
                              <ul class="text-custom">
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Manage Contracts
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Maintain IFRS16
                                  </li>
                                  <li>
                                      <i class="fas fa-angle-double-right"></i>	Standard Report 
                                  </li>
                                 
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                  
                  </div>


                  <div class="col-lg-5 col-md-12 mt-sm-3" style="margin-top: 54px !important">
                    <img class="img-fluid rounded" src="template/assets/images/sbp.png" alt="img">
                  </div>
                  
                </div>
                
              </div>
            </div>
          </div>
          </div>
            
    </div>
</section>
<!--Portfolio End-->