<div>
    <img class="img-fluid d-none d-sm-none d-md-block" src="template/assets/images/services-bg.jpg" alt="img" style="width:100%;height:300px">
</div>
<!--Services One Start-->
<section class="services-one py-5">
    <div class="about-one-bg wow slideInRight" data-wow-delay="100ms" data-wow-duration="2500ms"
         style="background-image: url(template/assets/images/about-one-bg.png);height:100%;"></div>
    <div class="services-one__top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="services-one__top-left">
                        <div class="section-title text-center">
                            <h3 class="section-title__title">Our Services</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="services-one__bottom">
        <div class="services-one__container">
            <div class="row">
                <!--Services One Single Start-->
                <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                    <div class="services-one__single">
                        <div class="service-one__img service_icon">
                            <img src="template/assets/images/service-1.png" alt="">
                        </div>
                        <div class="home-service-one__content">
                            <a href="#">
                            <h3 class="service-one__title">ERP Solution</h3></a>
                            <p>SBP is a ERP solution. It is a cloud based software that defines the business process itself.</p>
                        </div>
                    </div>
                </div>
                <!--Services One Single End-->
                <!--Services One Single Start-->
                <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                    <div class="services-one__single">
                        <div class="service-one__img service_icon">
                            <img src="template/assets/images/service-2.png" alt="">
                        </div>
                        <div class="home-service-one__content">
                            <a href="#">
                            <h2 class="service-one__title">Implementation</h2></a>
                            <p>Our consultants have extensive knowledge in managing various operations and managing ERP.</p>
                        </div>
                    </div>
                </div>
                <!--Services One Single End-->
                <!--Services One Single Start-->
                <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                    <div class="services-one__single">
                        <div class="service-one__img service_icon">
                            <img src="template/assets/images/service-3.png" alt="">
                        </div>
                        <div class="home-service-one__content">
                            <a href="#">
                            <h2 class="service-one__title">Improve Process</h2></a>
                            <p>We understand business process and importance of data security.</p>
                        </div>
                    </div>
                </div>
                <!--Services One Single End-->
                <!--Services One Single Start-->
                <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                    <div class="services-one__single">
                        <div class="service-one__img service_icon">
                            <img src="template/assets/images/service-4.png" alt="">
                        </div>
                        <div class="home-service-one__content">
                            <a href="#">
                            <h2 class="service-one__title">Outsourcing</h2></a>
                            <p>Reducing expenditure by outsourcing non-performing activities in the field of Finance and IT.</p>
                        </div>
                    </div>
                </div>
                <!--Services One Single End-->
                <!--Services One Single Start-->
                <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                    <div class="services-one__single">
                        <div class="service-one__img service_icon">
                            <img src="template/assets/images/service-5.png" alt="">
                        </div>
                        <div class="home-service-one__content">
                            <a href="#">
                            <h2 class="service-one__title">Cloud Solution</h2></a>
                            <p>Customized ‘Standalone’ and ‘Hybrid’ solution options are available according to customer needs.</p>
                        </div>
                    </div>
                </div>
                <!--Services One Single End-->
                <!--Services One Single Start-->
                <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                    <div class="services-one__single">
                        <div class="service-one__img service_icon">
                            <img src="template/assets/images/service-6.png" alt="">
                        </div>
                        <div class="home-service-one__content">
                            <a href="#">
                            <h2 class="service-one__title">Manage Server</h2></a>
                            <p>We manage the process of keeping a server software updated and running so that a computer network can operate smoothly.</p>
                        </div>
                    </div>
                </div>
                <!--Services One Single End-->
            </div>
        </div>
    </div>
</section>
<!--Services One End-->
