<div>
    <img class="img-fluid d-none d-sm-none d-md-block" src="app/assets/images/contact-bg.jpg" alt="img" style="width:100%;height:300px">
</div>
       <!--Contact Page Start-->
        <section class="contact-page">
            <div class="about-one-bg wow slideInRight" data-wow-delay="100ms" data-wow-duration="2500ms"
         style="background-image: url(app/assets/images/about-one-bg.png);height:100%;"></div>
            <div class="container">
                <div class="row">
                    <div class="col-xl-4 col-lg-4">
                        <div class="contact-page__left">
                            <div class="section-title text-left">
                                <div class="section-sub-title-box">
                                </div>
                                <h2 class="section-title__title">GET IN TOUCH</h2>
                            </div>

                        <h5>Canada :</h5>
                        <p style="color: #000">Business, Technology and Process Inc.</p>
                            
                            
                            <div class="d-flex flex-row">
                                <div class="p-2 contact-page-icon"><i class="icon">
                                <span class="icon-pin"></span>
                            </i></div>
                                <div class="p-2"><p class="contact-page__call-number">N2T2X8, Waterloo, ON, Canada.
                                </p>
                                </div>
                                </div>

                                <div class="d-flex flex-row">
                                    <div class="p-2 contact-page-icon"><i class="fa fa-phone"></i></div>
                                    <div class="p-2"><a href="callto:+12269295981" class="contact-page__call-number">+1 226 929 5981 </a></div>
                                    </div>

                        <h5 class="mt-2">Bangladesh :</h5>
                        <p style="color: #000">btp Bangladesh Ltd.</p>
                            
                            
                            <div class="d-flex flex-row">
                                <div class="p-2 contact-page-icon"><i class="icon">
                                <span class="icon-pin"></span>
                            </i></div>
                                <div class="p-2"><p class="contact-page__call-number">House - 12&14, Road - 8/1, Block - D, 
                                    Banasree, Rampura, Dhaka – 1219.
                                    
                                </p>
                                </div>
                                </div>
                                <div class="d-flex flex-row">
                                    <div class="p-2 contact-page-icon"><i class="fa fa-phone"></i></div>
                                    <div class="p-2"><a href="callto:+8801961693396" class="contact-page__call-number">+8801961693396 </a></div>
                                    </div>
                                    <div class="d-flex flex-row">
                                        <div class="p-2 contact-page-icon"><i class="fa fa-envelope"></i></div>
                                        <div class="p-2"><a href="mailto:info@btp-inc.ca" class="contact-page__call-number">info@btp-inc.ca</a></div>
                                        </div>
                        </div>
                    </div>
                    <div class="col-xl-8 col-lg-8">
                        <div class="contact-page__right">
                            <div class="contact-page__form">
                                <form action="{{ route('send.email') }}" class="comment-one__form" method="post">
                                
                             
                                    <div class="row">
                                        <div class="col-xl-6">
                                            <div class="comment-form__input-box">
                                                <input type="text" placeholder="Your name" name="name" required>
                                            </div>
                                        </div>
                                        <div class="col-xl-6">
                                            <div class="comment-form__input-box">
                                                <input type="email" placeholder="Email address" name="email" required>
                                            </div>
                                        </div>
                                        <div class="col-xl-6">
                                            <div class="comment-form__input-box">
                                                <input type="text" placeholder="Phone number" name="phone" required>
                                            </div>
                                        </div>
                                        <div class="col-xl-6">
                                            <div class="comment-form__input-box">
                                                <input type="text" placeholder="Subject" name="subject" required>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xl-12">
                                            <div class="comment-form__input-box text-message-box">
                                                <textarea name="message" placeholder="Write a message"></textarea>
                                            </div>
                                            <div class="comment-form__btn-box">
                                                <button type="submit" class="thm-btn comment-form__btn" style="background-color: #00B5E2">Send a
                                                    Message</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>