  <!--Main Slider Start-->
  <section class="slider-section">
    <div id="carousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carousel" data-slide-to="0" class="active"></li>
            <li data-target="#carousel" data-slide-to="1"></li>
        </ol>

        <div class="carousel-inner" role="listbox">

            <div class="carousel-item active" style="background-image: url(app/assets/images/slider-1-1.jpg); background-size: cover;">
                <div class="overlay"></div> <!-- Add an overlay div here -->
                <div class="caption">
                    <div class="main-slider__title">

                    </div>
                </div>
            </div>

            <div class="carousel-item" style="background-image: url(app/assets/images/slider-1-2.jpg); background-size: cover;">
                <div class="overlay"></div> <!-- Add an overlay div here -->
                <div class="caption">
                </div>
            </div>
        </div>

        <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
  </section>

    <!--Main Slider End-->
    <!--About One Start-->
    <section class="about-one py-5">
        <div class="about-one-bg wow slideInRight" data-wow-delay="100ms" data-wow-duration="2500ms"
             style="background-image: url(app/assets/images/about-one-bg.png);height:100%;"></div>
             <div class="container">
                <div class="row">
                    <div class="col-md-12 col-lg-6">
                        <img class="img-fluid rounded mb-3" src="app/assets/images/about-img.jpg" alt="img">
                      </div>
                  <div class="col-md-12 col-lg-6 align-self-center" style="color: black">
                    <h3 class="section-title__title">About The Company</h3>
                    <p class="about-one__text-2">Business, Technology and Process Inc. (BTP), a Canadian IT solution provider. btp has number of Qualified Accountants, IT Professionals and few Strategic partners. <a class="text-primary" href="about-us">More Details</a> </p>
                    <ul class="text-custom">
                        <li style="font-weight: 600">
                            Our Strategic Partners
                        </li>
                        <li>
                                In Canada: Accounting Harbor (Accounting Firm)
                        </li>
                        <li>
                                In USA: Synergy Technology Solutions LLC (IT firm and our global distributor)
                        </li>
                        <li>
                                In Bangladesh: Howladar Yunus and Co. (Audit Firm)
                        </li>
                        <li>
                                In Bangladesh: btp Bangladesh Ltd. (IT Firm)
                        </li>
                    </ul>
                  </div>

                </div>
              </div>
    </section>
    <!--About One End-->

    <!--Why choose Us Start-->
    <section id="Why-choose" class="py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-lg-6 align-self-center mb-3">
                <h3 class="section-title__title mb-4">Why Choosing Us</h3>
                <ul class="text-custom" style="color: black">
                    <li>
                        <i class="fas fa-angle-double-right about-one__text-2"></i>	Our consultants have extensive knowledge in managing various operations and implementing ERP
                    </li>
                    <li>
                        <i class="fas fa-angle-double-right about-one__text-2"></i>	We understand business process and the importance of data security
                    </li>
                    <li>
                        <i class="fas fa-angle-double-right about-one__text-2"></i>	We can help you to reduce your cost at significant level
                    </li>
                    <li>
                        <i class="fas fa-angle-double-right about-one__text-2"></i>	Our online features can save your time and investment on equipment
                    </li>
                    <li>
                        <i class="fas fa-angle-double-right about-one__text-2"></i>	We help clients to improve efficiencies so that they can focus into their core business
                    </li>
                </ul>
            </div>
            <div class="col-md-12 col-lg-6">
              <img class="img-fluid rounded" src="app/assets/images/image5.jpeg" alt="img">
            </div>
          </div>
        </div>
       </section>
<!--Why choose Us End-->

    <!--Services One Start-->
    <section class="services-one py-5">
        <div class="about-one-bg wow slideInRight" data-wow-delay="100ms" data-wow-duration="2500ms"
             style="background-image: url(app/assets/images/service-bg.jpg);height:100%;"></div>
        <div class="services-one__top">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="services-one__top-left">
                            <div class="section-title text-center">
                                <h3 class="section-title__title">Our Services</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="services-one__bottom">
            <div class="services-one__container">
                <div class="row">
                    <!--Services One Single Start-->
                    <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                        <div class="services-one__single">
                            <div class="service-one__img service_icon">
                                <img src="app/assets/images/service-1.png" alt="">
                            </div>
                            <div class="home-service-one__content">
                                <a href="services">
                                <h2 class="service-one__title">ERP Solution</h2></a>
                            </div>
                        </div>
                    </div>
                    <!--Services One Single End-->
                    <!--Services One Single Start-->
                    <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                        <div class="services-one__single">
                            <div class="service-one__img service_icon">
                                <img src="app/assets/images/service-2.png" alt="">
                            </div>
                            <div class="home-service-one__content">
                                <a href="services">
                                <h2 class="service-one__title">Implementation</h2></a>
                            </div>
                        </div>
                    </div>
                    <!--Services One Single End-->
                    <!--Services One Single Start-->
                    <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                        <div class="services-one__single">
                            <div class="service-one__img service_icon">
                                <img src="app/assets/images/service-3.png" alt="">
                            </div>
                            <div class="home-service-one__content">
                                <a href="services">
                                <h2 class="service-one__title">Improve Process</h2></a>
                            </div>
                        </div>
                    </div>
                    <!--Services One Single End-->
                    <!--Services One Single Start-->
                    <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                        <div class="services-one__single">
                            <div class="service-one__img service_icon">
                                <img src="app/assets/images/service-4.png" alt="">
                            </div>
                            <div class="home-service-one__content">
                                <a href="services">
                                <h2 class="service-one__title">Outsourcing</h2></a>
                            </div>
                        </div>
                    </div>
                    <!--Services One Single End-->
                    <!--Services One Single Start-->
                    <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                        <div class="services-one__single">
                            <div class="service-one__img service_icon">
                                <img src="app/assets/images/service-5.png" alt="">
                            </div>
                            <div class="home-service-one__content">
                                <a href="services">
                                <h2 class="service-one__title">Cloud Solution</h2></a>
                            </div>
                        </div>
                    </div>
                    <!--Services One Single End-->
                    <!--Services One Single Start-->
                    <div class="col-xl-4 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                        <div class="services-one__single">
                            <div class="service-one__img service_icon">
                                <img src="app/assets/images/service-6.png" alt="">
                            </div>
                            <div class="home-service-one__content">
                                <a href="services">
                                <h2 class="service-one__title">Manage Server</h2></a>
                            </div>
                        </div>
                    </div>
                    <!--Services One Single End-->
                </div>
            </div>
        </div>
    </section>
    <!--Services One End-->

    <!--Portfolio Start-->
    <section id="portfolio" class="py-5">
        <div class="container" style="color: black">
            <div class="section-title text-center">
                <h3 class="section-title__title mb-4">Our Product</h3>
                <h3 class="text-[20px]">SBP(Standard Business Practice)</h3>
                <p>
                    The name of our ERP solution is SBP. It is a cloud based which defines the business process itself.
                </p>
            </div>
          <div class="row">
            <div class="col-md-12 col-lg-6">
                <img class="img-fluid rounded mb-4" src="app/assets/images/sbp.png" alt="img">
              </div>
            <div class="col-md-12 col-lg-6 align-self-center">
                <h5 class="mb-2" style="font-weight: 900">The distinctive feature of SBP are</h5>
                            <ul class="text-custom">
                                <li>
                                    <i class="fas fa-angle-double-right"></i>	SBP modules are integrated, complies with all accounting standard and norms.
                                </li>
                                <li>
                                    <i class="fas fa-angle-double-right"></i>	User friendly and easy to train resources.
                                </li>
                                <li>
                                    <i class="fas fa-angle-double-right"></i>	Ensure strong internal control, secure database and returns very low audit risk.
                                </li>
                                <li>
                                    <i class="fas fa-angle-double-right"></i>	The rules and privileges are well defined and users are restricted by their assigned rules..
                                </li>
                                <li>
                                    <i class="fas fa-angle-double-right"></i>	Build on restful API making the server communication very lightweight and faster.
                                </li>
                                <li>
                                    <i class="fas fa-angle-double-right"></i>	Capable to run with any web browser.
                                </li>
                                <li class="">
                                    <a class="text-primary" href="products"> More Details...</a>
                                </li>
                            </ul>

            </div>

          </div>
        </div>
       </section>